# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
